#Comando para rodar esta automação para subir a aplicação: docker-compose up --build backend

version: '4.0.5'
services:
  backend:
    container_name: backend
    restart: always
    #o build aponta para o arquivo DockerFile e assim os comandos são executados
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq #é o rabbitmq abaixo e a aplicação e o rabbit precisam ficar na mesma rede.
                 #para as requisições funcionarem e configuração dos applications.properties funcionarem
                 #Nesta linha ele executa os comandos abaixo e de pois volta para o NETWORK e sobe a aplicação
    networks:
      host:

  rabbitmq:
    image: rabbitmq:4.0.5-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
     - '5672:5672'
     - '15672:15672'
    networks:
      host:

networks:
  host: